In [2]:
duration= 5
convexity = 75
yieldchange = -0.01

def changevalue(duration,convexity,yieldchange):
    return -(duration*yieldchange)+0.5*convexity*yieldchange**2

changevalue(duration,convexity,yieldchange)

0.053750000000000006

### From daily to yearly

For average returns
$$\bar{R}^{A}=\left(1+\bar{R}^{W}\right)^{52}-1=\left(1+\bar{R}^{D}\right)^{252}-1$$


If you have log returns, you can simply use the arithmetic average (calculated by prices):
$$\bar{r}=\frac{1}{k} \sum_{i=1}^{N} r_{t-i+1}$$
and to annualise
$$\bar{r}^{A}=52 \times \bar{r}^{W}=252 \times \bar{r}^{D}$$

In [5]:
r_daily=0.0008

r_yearly=(1+r_daily)**252-1
print(r_yearly)
r_weekly = (1+r_daily)**52-1
print(r_weekly)

0.22325997172399203
0.042460066945947395


In [4]:
r_monthly1=0.015
r_yearly1 = (1+r_monthly1)**12-1
r_yearly1


0.19561817146153393

Standard deviation $$\sigma_Y^2=252\sigma_D^2$$

In [7]:
import numpy as np

var_daily=0.0005
var_yearly= var_daily*252
std_yearly=np.sqrt(var_yearly)
print(std_yearly)

0.35496478698597694


In [9]:
std_weekly=0.05
std_yearly1=std_weekly*np.sqrt(52)
print(std_yearly1)

0.36055512754639896


# Two assets portfolio

$$\begin{aligned} A &=\left[\begin{array}{llll}{\mu} & {1}\end{array}\right]^{\prime} \Sigma^{-1}\left[\begin{array}{ll}{\mu} & {1}\end{array}\right] \\ &=\left[\begin{array}{lll}{\mu^{\prime} \Sigma^{-1} \mu} & {\mu^{\prime} \Sigma^{-1} 1} \\ {\mu^{\prime} \Sigma^{-1} 1} & {1^{\prime} \Sigma^{-1} 1}\end{array}\right]:=\left[\begin{array}{ll}{a} & {b} \\ {b} & {c}\end{array}\right] \end{aligned}$$
and the inverse of a is:
$$A^{-1}=\frac{1}{a c-b^{2}}\left[\begin{array}{cc}{c} & {-b} \\ {-b} & {a}\end{array}\right]$$

In [45]:
mu_1=0.31
mu_2=0.43
std_1=0.27
std_2= 0.45
corr = 0.64
def MUmat(mu1,mu2):
    return np.array([[mu1,1],[mu2,1]])

mu_matrix1=MUmat(mu_1,mu_2)

def Emat(std1,std2,correlation):
    return np.array([[std1**2,correlation*std1*std2],[correlation*std1*std2,std2**2]])

In [46]:
E = Emat(std_1,std_2,corr)
E

array([[0.0729 , 0.07776],
       [0.07776, 0.2025 ]])

In [47]:
def Amat(mu_matrix,SIGMAmatrix):
    return np.dot(np.transpose(mu_matrix),np.dot(np.linalg.inv(SIGMAmatrix),mu_matrix))

A= Amat(mu_matrix1,E)

In [71]:
A

array([[ 1.40077546,  4.19701042],
       [ 4.19701042, 13.75459571]])

In [48]:
mu_matrix1

array([[0.31, 1.  ],
       [0.43, 1.  ]])

### Efficient Frontier
Standard deviation as a function of portfolio return:
$$\sigma_{P}=\sqrt{\frac{c \mu_{P}^{2}-2 b \mu_{P}+a}{a c-b^{2}}}$$

Global minimum variance portfolio
$$\mu_{g m v}=b / c$$
$$\sigma_{g m v}^{2}=1 / c$$

In [63]:
mu_gmv=A[0,1]/A[1,1]
print(mu_gmv)
std_gmv= 1/np.sqrt(A[1,1])
print(std_gmv)


0.3051351351351351
0.26963488827110815


In [51]:
weights= (1/A[1,1])*np.dot(np.linalg.inv(E),np.ones(2))
print(weights)

[ 1.04054054 -0.04054054]


In [53]:
def muexcess(mu1,mu2,riskfree):
    return np.array([mu1-riskfree,mu2-riskfree])

In [54]:
rf=0.1
mu_e=muexcess(mu_1,mu_2,rf)

the optimal portfolio weights for specific expected excess return $\mu_P^e$ is:
$$\boldsymbol{w}=\boldsymbol{\Sigma}^{-1} \boldsymbol{\mu}^{e} \frac{\mu_{P}^{e}}{\left(\boldsymbol{\mu}^{e}\right)^{\top} \boldsymbol{\Sigma}^{-1} \boldsymbol{\mu}^{e}}$$

it follows that minimal portfolio variance for specific expected excess return $\mu_P^e$ is:
$$\sigma_{P}^{2}=\frac{\left(\mu_{P}^{e}\right)^{2}}{\left(\mu^{e}\right)^{\top} \Sigma^{-1} \mu^{e}}$$

The link between $\sigma_P$ and of  $\mu_P^e$ is:
$$\sigma_{P}=\frac{\mu_{P}^{e}}{\sqrt{\left(\boldsymbol{\mu}^{e}\right)^{\top} \boldsymbol{\Sigma}^{-1} \boldsymbol{\mu}^{e}}}$$
or equivalently (this is called the Capital Market Line):
$$\mu_{P}=\sigma_{P} \sqrt{\left(\boldsymbol{\mu}^{e}\right)^{\top} \boldsymbol{\Sigma}^{-1} \boldsymbol{\mu}^{e}}+\mu_{0}$$

### Tangent Portfolio
The portfolio where everything is invested in risky assets is called the tangent portfolio. The excess return of the tangent portfolio is:
$$\mu_{\tan }^{e}=\frac{\left(\boldsymbol{\mu}^{e}\right)^{\top} \boldsymbol{\Sigma}^{-1} \boldsymbol{\mu}^{e}}{\mathbf{1}^{\prime} \boldsymbol{\Sigma}^{-1} \boldsymbol{\mu}^{e}}$$
with:
$$\begin{array}{l}{\sigma_{t a n}=\frac{\sqrt{\left(\boldsymbol{\mu}^{e}\right)^{\top} \boldsymbol{\Sigma}^{-1} \boldsymbol{\mu}^{e}}}{\mathbf{1}^{\prime} \boldsymbol{\Sigma}^{-1} \boldsymbol{\mu}^{e}}} \\ {\boldsymbol{w}_{t a n}=\boldsymbol{\Sigma}^{-1} \boldsymbol{\mu}^{e} \frac{1}{\mathbf{1}^{\top} \boldsymbol{\Sigma}^{-1} \boldsymbol{\mu}^{e}}}\end{array}$$

In [57]:
mue_tan=(np.dot(np.transpose(mu_e),np.dot(np.linalg.inv(E),mu_e)))/(np.dot(np.ones(2),np.dot(np.linalg.inv(E),mu_e)))
mue_tan

0.24770750988142287

In [59]:
std_tan=np.sqrt(np.dot(np.transpose(mu_e),np.dot(np.linalg.inv(E),mu_e)))/(np.dot(np.ones(2),np.dot(np.linalg.inv(E),mu_e)))
std_tan

0.2962959027898122

In [60]:
w_tan=(np.dot(np.linalg.inv(E),mu_e))/(np.dot(np.ones(2),np.dot(np.linalg.inv(E),mu_e)))
w_tan

array([0.68577075, 0.31422925])

In [70]:
SR_1=(mu_1-rf)/std_1
print('Sharpe Ratio asset 1: %f'%SR_1)
SR_2=(mu_2-rf)/std_2
print('Sharpe Ratio asset 2: %f'%SR_2)
SR_gmv=(mu_gmv-rf)/std_gmv
print('Sharpe Ratio Global minimum variance: %f'%SR_gmv)
SR_tan=(mue_tan)/std_tan
print('Sharpe Ratio Tangent portfolio: %f'%SR_tan)



Sharpe Ratio asset 1: 0.777778
Sharpe Ratio asset 2: 0.733333
Sharpe Ratio Global minimum variance: 0.760789
Sharpe Ratio Tangent portfolio: 0.836014
